
		// This class was auto-generated by AnimationCooker
		using System.Collections.Generic;
		public static class AnimDb
		{
			public static void Populate(DoubleDictionary<string, AnimDbEntry> dict)
			{
				dict["Sparrow", "Attack"] = new AnimDbEntry { beginFrame = 0, endFrame = 4, interval = 0.07692308f, modelName = "Sparrow", clipName = "Attack", modelIndex = 0, clipIndex = 0 };
				dict["Sparrow", "Bounce"] = new AnimDbEntry { beginFrame = 5, endFrame = 9, interval = 0.07692308f, modelName = "Sparrow", clipName = "Bounce", modelIndex = 0, clipIndex = 1 };
				dict["Sparrow", "Clicked"] = new AnimDbEntry { beginFrame = 10, endFrame = 14, interval = 0.07692308f, modelName = "Sparrow", clipName = "Clicked", modelIndex = 0, clipIndex = 2 };
				dict["Sparrow", "Death"] = new AnimDbEntry { beginFrame = 15, endFrame = 19, interval = 0.07692308f, modelName = "Sparrow", clipName = "Death", modelIndex = 0, clipIndex = 3 };
				dict["Sparrow", "Eat"] = new AnimDbEntry { beginFrame = 20, endFrame = 24, interval = 0.07692308f, modelName = "Sparrow", clipName = "Eat", modelIndex = 0, clipIndex = 4 };
				dict["Sparrow", "Fear"] = new AnimDbEntry { beginFrame = 25, endFrame = 29, interval = 0.07692308f, modelName = "Sparrow", clipName = "Fear", modelIndex = 0, clipIndex = 5 };
				dict["Sparrow", "Fly"] = new AnimDbEntry { beginFrame = 30, endFrame = 34, interval = 0.07692308f, modelName = "Sparrow", clipName = "Fly", modelIndex = 0, clipIndex = 6 };
				dict["Sparrow", "Hit"] = new AnimDbEntry { beginFrame = 35, endFrame = 39, interval = 0.07692308f, modelName = "Sparrow", clipName = "Hit", modelIndex = 0, clipIndex = 7 };
				dict["Sparrow", "Idle_A"] = new AnimDbEntry { beginFrame = 40, endFrame = 44, interval = 0.07692308f, modelName = "Sparrow", clipName = "Idle_A", modelIndex = 0, clipIndex = 8 };
				dict["Sparrow", "Idle_B"] = new AnimDbEntry { beginFrame = 45, endFrame = 49, interval = 0.07692308f, modelName = "Sparrow", clipName = "Idle_B", modelIndex = 0, clipIndex = 9 };
				dict["Sparrow", "Idle_C"] = new AnimDbEntry { beginFrame = 50, endFrame = 54, interval = 0.07692308f, modelName = "Sparrow", clipName = "Idle_C", modelIndex = 0, clipIndex = 10 };
				dict["Sparrow", "Jump"] = new AnimDbEntry { beginFrame = 55, endFrame = 59, interval = 0.07692308f, modelName = "Sparrow", clipName = "Jump", modelIndex = 0, clipIndex = 11 };
				dict["Sparrow", "Roll"] = new AnimDbEntry { beginFrame = 60, endFrame = 64, interval = 0.07692308f, modelName = "Sparrow", clipName = "Roll", modelIndex = 0, clipIndex = 12 };
				dict["Sparrow", "Run"] = new AnimDbEntry { beginFrame = 65, endFrame = 69, interval = 0.07692308f, modelName = "Sparrow", clipName = "Run", modelIndex = 0, clipIndex = 13 };
				dict["Sparrow", "Sit"] = new AnimDbEntry { beginFrame = 70, endFrame = 74, interval = 0.07692308f, modelName = "Sparrow", clipName = "Sit", modelIndex = 0, clipIndex = 14 };
				dict["Sparrow", "Spin"] = new AnimDbEntry { beginFrame = 75, endFrame = 79, interval = 0.07692308f, modelName = "Sparrow", clipName = "Spin", modelIndex = 0, clipIndex = 15 };
				dict["Sparrow", "Swim"] = new AnimDbEntry { beginFrame = 80, endFrame = 84, interval = 0.07692308f, modelName = "Sparrow", clipName = "Swim", modelIndex = 0, clipIndex = 16 };
				dict["Sparrow", "Walk"] = new AnimDbEntry { beginFrame = 85, endFrame = 89, interval = 0.07692308f, modelName = "Sparrow", clipName = "Walk", modelIndex = 0, clipIndex = 17 };
			}
			public enum Model { Sparrow }
			public enum Sparrow { Attack, Bounce, Clicked, Death, Eat, Fear, Fly, Hit, Idle_A, Idle_B, Idle_C, Jump, Roll, Run, Sit, Spin, Swim, Walk}
		}